routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/{locale}/lang', function ($locale) {
    if (!in_array($locale, config('app.supported_locales'))) {
        abort(400);
    }

    session()->put('locale', $locale);
    return redirect()->back();
})->name('locale');

Auth::routes(['verify' => true]);

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('users/change_password', [\App\Http\Controllers\Panel\UsersController::class, 'changePassword'])->name('users.change_password');
Route::post('users/update_password', [\App\Http\Controllers\Panel\UsersController::class, 'updatePassword'])->name('users.update_password');

Route::get('users/setup_curriences', [\App\Http\Controllers\Panel\UsersController::class, 'setupCurrencies']);
Route::post('users/setup_curriences', [\App\Http\Controllers\Panel\UsersController::class, 'saveUserCurrencies'])->name('users.setup_curriences');

Route::get('users/checkOdd', [\App\Http\Controllers\Panel\UsersController::class, 'checkOdd']);

Route::resource('users', \App\Http\Controllers\Panel\UsersController::class);

resources/views/layouts/menu/guest_menu.blade.php
@if (Route::has('login'))
    <li class="nav-item">
        <a class="nav-link" href="{{ route('login') }}">@lang('base.login_nav')</a>
    </li>
@endif

@if (Route::has('register'))
    <li class="nav-item">
        <a class="nav-link" href="{{ route('register') }}">@lang('base.register_nav')</a>
    </li>
@endif

resources/views/layouts/menu/logged_user_menu.blade.php
<li class="nav-item dropdown">
    <a id="navbarDropdown" href="javascript:void(0)" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="avatar rounded-circle nav-link dropdown-toggle" v-pre>
        <img alt="avatar" class="user-avatar-md img-fluid rounded-circle" src="{{ Auth::user()->avatar }}">
        {{ Auth::user()->name }}
    </a>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ route('users.setup_curriences') }}"> @lang('base.user.currencies_setup') </a>
        <a class="dropdown-item" href="{{ route('users.edit', auth()->id()) }}"> @lang('base.user.edit_profile') </a>
        <a class="dropdown-item" href="{{ route('users.change_password') }}"> @lang('base.user.change_password') </a>

        <a class="dropdown-item" data-alert="{{json_encode(__('base.user.alert'))}}"  id="delete_account" href="javascript:void(0)"> @lang('base.user.delete_account') </a>
        <form id="delete_user" action="{{ route('users.destroy', auth()->id()) }}" method="POST" class="d-none">
            {{method_field('DELETE')}}
            @csrf
        </form>

        <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            @lang('base.logout')
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
    </div>
</li>